[Fix] Support for resolving parent route's descendants
wso2/identity-apps pull request #1573
Opened 2021-01-25 06:52 UTC by yasinmiran

## Purpose
> Please note $subject

2021-01-25 19:21 UTC, DimalChandrasiri approved these changes

2021-02-02 07:41 UTC, brionmario commented
Shall we check if the scenario mentioned in [this issue](https://github.com/wso2/product-is/issues/10594) works as expected? @yasinmiran

2021-02-02 07:42 UTC, brionmario requested changes
Shall we check if the scenario mentioned in this issue works as expected? @yasinmiran

2021-02-16 03:50 UTC, yasinmiran commented
This PR has been tested against the previous issue https://github.com/wso2/product-is/issues/10594

2021-02-16 04:07 UTC, inthirakumaaran approved these changes

2021-02-16 04:52 UTC, brionmario approved these changes

2021-02-16 05:10 UTC, merged