Modify Active Sessions tab in user edit view
wso2/identity-apps pull request #2140
Opened 2021-06-14 10:49 UTC by kayathiri4

### Purpose
> Make modifications to the Active Sessions vies and remove the terminate session button for active sessions list view.

### Checklist
- [ ] e2e cypress tests locally verified.
- [ ] Manual test round performed and verified.
- [ ] UX/UI review done on final implementation
- [ ] Documentation provided. (Add links)
- [ ] Unit tests provided. (Add links if any)
- [ ] Integration tests provided. (Add links if any)

### Security checks
- [ ] Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines?
- [ ] Ran FindSecurityBugs plugin and verified report?
- [ ] Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?

2021-06-14 16:52 UTC, NipuniBhagya requested changes

2021-06-14 16:52 UTC, NipuniBhagya commented on apps/console/src/features/users/components/user-sessions.tsx
> +                                                    <p style={ { fontSize: "11px" } }>
Let's not add inline styles, please.

2021-06-15 10:12 UTC, thivi approved these changes

2021-06-15 11:00 UTC, NipuniBhagya requested changes

2021-06-15 14:16 UTC, brionmario approved these changes

2021-06-15 16:06 UTC, NipuniBhagya approved these changes

2021-06-16 05:58 UTC, merged