Organization Changes
wso2/identity-apps pull request #2440
Opened 2021-09-07 06:15 UTC by rdranathunga

### Purpose
> Describe the problem, feature, improvement or the change introduces by the PR briefly. Add screenshots/GIFs if UI/UX changes are introduced. Remove this placeholder when you're editing.

### Related Issues
- Issue `#1` or (None)

### Checklist
- [ ] e2e cypress tests locally verified.
- [ ] Manual test round performed and verified.
- [ ] UX/UI review done on final implementation.
- [ ] Documentation provided. (Add links if there's any)
- [ ] Unit tests provided. (Add links if there's any)
- [ ] Integration tests provided. (Add links if there's any)

### Related PRs
- Related PR `#1` or (None)

### Security checks
- [ ] Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines?
- [ ] Ran FindSecurityBugs plugin and verified report?
- [ ] Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?

2021-09-07 06:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/identity-apps?pullRequest=2440) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/identity-apps?pullRequest=2440) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/identity-apps?pullRequest=2440) it.</sub>

2021-10-04 03:05 UTC, yasinmiran commented
cc:// @brionmario @thivi @DimalChandrasiri @NipuniBhagya @thanujalk @jeradrutnam

2021-10-05 17:49 UTC, thivi requested changes

2021-10-05 17:49 UTC, thivi commented on apps/console/src/features/core/components/organisation-advanced-search.tsx
> +/* eslint-disable sort-keys */
Shall we remove these comments?

2021-10-05 17:49 UTC, thivi commented on apps/console/src/features/core/components/organisation-advanced-search.tsx
> + * Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
The year should be 2021

2021-10-05 17:49 UTC, thivi commented on apps/console/src/features/core/components/pagination.tsx
> +/* eslint-disable max-len */
Shall we remove this line and add a license header?

2021-10-05 17:49 UTC, thivi commented on apps/console/src/features/data/country.js
> +/* eslint-disable object-curly-spacing */
Shall we remove these comments disabling eslint? Check the other places as well.

2022-01-18 09:58 UTC, brionmario commented
Closing since there is an ongoing effort on some improvements on top of this PR

2022-01-18 09:58 UTC, closed without merging