Update the avatar of IDP icons in linked social accounts
wso2/identity-apps pull request #3077
Opened 2022-06-08 12:56 UTC by ShanChathusanda93

### Purpose
* Updated the IDP avatar in the linked social accounts section in myaccount.

2022-06-08 13:26 UTC, brionmario approved these changes

2022-06-15 10:05 UTC, yasinmiran requested changes

2022-06-15 10:05 UTC, yasinmiran commented on modules/theme/src/themes/default/views/card.overrides
> +                        }
```suggestion

                        .associations-list-avatar-wrapper {
                            display: flex;
                            align-items: center;
                            column-gap: 5px;
                        }
```

2022-06-15 10:05 UTC, yasinmiran commented on modules/theme/src/themes/default/views/card.overrides
> +                        .associations-list-avatar-wrapper {
This should be in the `list.overrides` file right?

2022-06-15 16:07 UTC, ShanChathusanda93 commented on apps/myaccount/src/components/federated-associations/federated-associations.tsx
> +                                                <div style={{display: "flex", alignItems: "center", columnGap:"5px"}}>
Moved to `list.overrides` file

2022-06-15 16:07 UTC, ShanChathusanda93 commented on modules/theme/src/themes/default/views/card.overrides
> +                        }
Applied the changes.

2022-06-16 04:42 UTC, yasinmiran approved these changes

2022-06-16 06:27 UTC, merged