Added password validation check within myaccount change password section
wso2/identity-apps pull request #3142
Opened 2022-07-07 08:56 UTC by gershom96

### Purpose
The change password section in myaccount did not have a password validation section. This was added in this PR.

### Checklist
- [ ] e2e cypress tests locally verified.
- [ ] Manual test round performed and verified.
- [ ] UX/UI review done on the final implementation.
- [ ] Documentation provided. (Add links if there are any)
- [ ] Unit tests provided. (Add links if there are any)
- [ ] Integration tests provided. (Add links if there are any)

### Security checks
- [ ] Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines?
- [ ] Ran FindSecurityBugs plugin and verified report?
- [ ] Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?

2022-07-07 08:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/identity-apps?pullRequest=3142) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/identity-apps?pullRequest=3142) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/identity-apps?pullRequest=3142) it.</sub>

2022-07-08 06:41 UTC, yasinmiran requested changes

2022-07-08 06:41 UTC, yasinmiran commented on apps/myaccount/src/components/change-password/change-password.tsx
> +        class : string;
Avoid using `class` or any keywords in attribute namespaces.

```suggestion
        cssClassName : string;
```

2022-07-08 06:41 UTC, yasinmiran commented on apps/myaccount/src/components/change-password/change-password.tsx
> +            if (password === "") {
Use a constant

const EMPTY_STRING = "";

```suggestion
            if (password === EMPTY_STRING) {
```

2022-07-08 06:41 UTC, yasinmiran commented on apps/myaccount/src/components/change-password/change-password.tsx
> +        } else if ( id === "password-validation-case" ) {
No need to keep spaces inside before/after the parenthesis.
Let's use ESLint plugin to format the code.

```suggestion
        } else if (id === "password-validation-case") {
```

2022-07-08 06:41 UTC, yasinmiran commented on apps/myaccount/src/components/change-password/change-password.tsx
> +                                <Icon id = "password-validation-length" className = {getIconProps("password-validation-length").class} color = {getIconProps("password-validation-length").color}/>
No spaces before/after equal when passing down props. Please use ESLint.

```suggestion
                                <Icon id="password-validation-length" className={getIconProps("password-validation-length").class} color={getIconProps("password-validation-length").color}/>
```

2022-07-08 06:41 UTC, yasinmiran commented on apps/myaccount/src/components/change-password/change-password.tsx
> +                                <p>At least one uppercase and lowercase letter</p>
Shall we declare and get these strings from `i18n` module?

```suggestion
                                <p>At least one uppercase and lowercase letter</p>
```

2022-07-08 06:41 UTC, yasinmiran commented on apps/myaccount/src/components/change-password/change-password.tsx
> +                                <Icon id = "password-validation-number" className = {getIconProps("password-validation-number").class} color = {getIconProps("password-validation-number").color}/>
These lines are too long. Format props into multilines. Use ESLint.

```suggestion
                                <Icon id = "password-validation-number" className = {getIconProps("password-validation-number").class} color = {getIconProps("password-validation-number").color}/>
```

2022-07-08 06:41 UTC, yasinmiran commented on apps/myaccount/src/components/change-password/change-password.tsx
> +                iconProps.class = "remove " + iconProps.class
These conditions are bloated. You can simplify this into: -

```
const DEFAULT: IconProps = {
    cssClassName: "circle",
    color: "grey"
};

const POSITIVE: IconProps = {
    cssClassName: `${DEFAULT.cssClassName} check`,
    color: `green`
};

const NEGATIVE: IconProps = { ... }

if (password === "") {
    return DEFAULT;
} else if ( password.match(chars) ) {
    return POSITIVE;
} else {
    return NEGATIVE;
}
```

2022-07-11 05:47 UTC, DimalChandrasiri commented on apps/myaccount/src/components/change-password/change-password.tsx
> +    const getIconProps = (id : string) : IconProps =>{
Add a doc comment regarding the implementation and usage

2022-07-11 05:47 UTC, DimalChandrasiri commented on apps/myaccount/src/extensions/configs/models/password-validation.ts
> +export interface PasswordValidationConfig {
Update the license header to new one.

2022-07-11 05:48 UTC, DimalChandrasiri commented on apps/myaccount/src/extensions/configs/password-validation.ts
> +import { PasswordValidationConfig } from "./models/password-validation";
Update the license header to new one

2022-07-11 05:48 UTC, DimalChandrasiri approved these changes

2022-07-11 07:30 UTC, yasinmiran approved these changes

2022-07-11 10:44 UTC, merged

2022-07-12 08:47 UTC, gershom96 commented on apps/myaccount/src/components/change-password/change-password.tsx
> +                    { passwordValidationConfig.showPasswordValidation  &&
Add an enum for the id strings.

2022-07-12 08:49 UTC, gershom96 commented on apps/myaccount/src/components/change-password/change-password.tsx
> +                    { passwordValidationConfig.showPasswordValidation  &&
paranthesis preceding the form should start right after the &&

2022-11-02 04:30 UTC, wenodpathirana commented on apps/myaccount/src/components/change-password/change-password.tsx
> +                    { passwordValidationConfig.showPasswordValidation  &&
Additional space before `&&`

2022-11-02 04:31 UTC, wenodpathirana commented on modules/i18n/src/translations/en-US/portals/myaccount.ts
> +
remove the extra line.