Fix update button and certificate type toggle issues in SAML web application
wso2/identity-apps pull request #3217
Opened 2022-07-22 11:37 UTC by shashimalcse

### Purpose
Update button is not working when toggle between provide certificate and none certificate types in SAML web application.  Also user can toggle back to none type in the certification section if request signature validation is enabled. 

These issues are fixed in this PR.

### Related Issues
- Issue `#1` or (None)

### Related PRs
- Related PR `#1` or (None)

### Checklist
- [ ] e2e cypress tests locally verified.
- [ ] Manual test round performed and verified.
- [ ] UX/UI review done on the final implementation.
- [ ] Documentation provided. (Add links if there are any)
- [ ] Unit tests provided. (Add links if there are any)
- [ ] Integration tests provided. (Add links if there are any)

### Security checks
- [ ] Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines?
- [ ] Ran FindSecurityBugs plugin and verified report?
- [ ] Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?

2022-07-26 07:17 UTC, yasinmiran requested changes

2022-07-26 07:17 UTC, yasinmiran commented on modules/forms/src/components/field.tsx
> +                                        if(inputField?.onBefore && !inputField.onBefore(event,value)){
Use ESLint for formatting

```suggestion
                                        if (inputField?.onBefore && !inputField.onBefore(event, value)) {
```

2022-07-26 07:17 UTC, yasinmiran commented on apps/console/src/features/applications/components/settings/certificate/application-certificate-wrapper.tsx
> +
Remove these empty lines.

```suggestion
```

2022-07-26 07:17 UTC, yasinmiran commented on apps/console/src/features/applications/components/settings/certificate/application-certificate-wrapper.tsx
> +                                        const Certtype  =  value as CertificateTypeInterface;
Use camel case.

```suggestion
                                        const certType  =  value as CertificateTypeInterface;
```

2022-07-26 07:17 UTC, yasinmiran commented on apps/console/src/features/applications/components/settings/certificate/application-certificate-wrapper.tsx
> +    canDiscardCerticate?: () => boolean;
Correct the spellings of this variable

```suggestion
    canDiscardCertificate?: () => boolean;
```

2022-07-26 07:17 UTC, yasinmiran commented on apps/console/src/features/applications/components/forms/inbound-saml-form.tsx
> +                                    canDiscardCerticate = { ():boolean => !isRequestSignatureValidationEnabled }
```suggestion
                                    canDiscardCerticate = { (): boolean => !isRequestSignatureValidationEnabled }
```

2022-07-26 07:17 UTC, yasinmiran commented on apps/console/src/features/applications/components/forms/inbound-saml-form.tsx
> +                            if(selectedCertType === CertificateTypeInterface.NONE){
```suggestion
                            if (selectedCertType === CertificateTypeInterface.NONE) {
```

2022-07-27 06:21 UTC, yasinmiran approved these changes

2022-07-27 06:21 UTC, yasinmiran commented on apps/console/src/features/applications/components/settings/certificate/application-certificate-wrapper.tsx
> +                                        const certType  =  value as CertificateTypeInterface;
Use ESLint auto-formatting.

```suggestion
                                        const certType  =  value as CertificateTypeInterface;
```

2022-08-07 17:21 UTC, senthalan commented
Closing as the PR is in the open state for a while. Please feel free to reopen and merge if needed.

2022-08-08 05:53 UTC, merged

2023-03-16 06:04 UTC, lashinijay commented on apps/console/src/features/applications/components/settings/certificate/application-certificate-wrapper.tsx
> +
Shall we remove these unwanted new lines?

2023-05-11 03:43 UTC, shashimalcse commented on apps/console/src/features/applications/components/forms/inbound-saml-form.tsx
> +                                    canDiscardCertificate = { (): boolean => !isRequestSignatureValidationEnabled }
If there is a possibility that the conditions for discarding a certificate might become more complex in the future, having a function allows you to easily modify the logic right?