Displaying Application template name in the applications list of console
wso2/identity-apps pull request #3259
Opened 2022-08-01 10:51 UTC by malshan1998

### Purpose
> This improvement displays the name of the template from which an application is created from, in the console, in a separate column.

### Related Issues
- Issue `#1` https://github.com/wso2/product-is/issues/10681#issue-757081311
- Issue `#2` https://github.com/wso2/product-is/issues/13944
- Issue `#3` https://github.com/wso2/product-is/issues/14114

### Related PRs
- None

### Checklist
- [ ] e2e cypress tests locally verified.
- [ ] Manual test round performed and verified.
- [ ] UX/UI review done on the final implementation.
- [ ] Documentation provided. (Add links if there are any)
- [ ] Unit tests provided. (Add links if there are any)
- [ ] Integration tests provided. (Add links if there are any)

### Security checks
- [ ] Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines?
- [ ] Ran FindSecurityBugs plugin and verified report?
- [ ] Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?

2022-08-01 10:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/identity-apps?pullRequest=3259) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/identity-apps?pullRequest=3259) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/identity-apps?pullRequest=3259) it.</sub>

2022-08-02 04:04 UTC, yasinmiran requested changes

2022-08-02 04:04 UTC, yasinmiran commented on apps/console/src/features/applications/components/application-list.tsx
> +                    const customApplicationIds = new Set( [
```suggestion
                    const customApplicationIds = new Set([
```

2022-08-02 04:04 UTC, yasinmiran commented on apps/console/src/features/applications/pages/applications.tsx
> +    } = useApplicationList("advancedConfigurations,templateId",listItemLimit, listOffset, searchQuery);
```suggestion
    } = useApplicationList("advancedConfigurations,templateId", listItemLimit, listOffset, searchQuery);
```

2022-08-02 04:04 UTC, yasinmiran commented on apps/console/src/features/applications/components/application-list.tsx
> +                                <p>{template?.name}</p>
A `div` would suffice here. No need a `p` wrap.

2022-08-02 06:31 UTC, malshan1998 commented on apps/console/src/features/applications/components/application-list.tsx
> +
Done

2022-08-02 06:31 UTC, malshan1998 commented on apps/console/src/features/applications/components/application-list.tsx
> +        console.log("resolveTableColumns called")
Done

2022-08-02 06:31 UTC, malshan1998 commented on apps/console/src/features/applications/components/application-list.tsx
> +import _ from "lodash";
Done

2022-08-02 06:32 UTC, malshan1998 commented on apps/console/src/features/applications/components/application-list.tsx
> +                    const customApplicationIds = new Set( [
Done

2022-08-02 06:33 UTC, malshan1998 commented on apps/console/src/features/applications/components/application-list.tsx
> +                                <p>{template?.name}</p>
Done

2022-08-02 06:34 UTC, malshan1998 commented on apps/console/src/features/applications/pages/applications.tsx
> +    } = useApplicationList("advancedConfigurations,templateId",listItemLimit, listOffset, searchQuery);
Done

2022-08-02 09:00 UTC, malshan1998 commented on apps/console/src/features/applications/components/application-list.tsx
> +                        if (template_clone) {
templateClone

2022-08-02 09:00 UTC, malshan1998 commented on apps/console/src/features/applications/components/application-list.tsx
> +                        const template_clone = _.cloneDeep(template);
interface (applicationTemplates)

2022-08-02 09:01 UTC, malshan1998 commented on apps/console/src/features/applications/components/application-list.tsx
> +                                return template.templateId === "custom-application";
"custom-application" : json

2022-08-05 04:36 UTC, malshan1998 commented
Closing due to errors in version control. Will resolve the errors in a separate branch and send a PR.

2022-08-05 04:36 UTC, closed without merging